version: "3"

services:

  sysinfo:
    image: sysinfo:latest
    container_name: sysinfo
    restart: on-failure
    command: [ ]
    volumes:
      - /proc:/proc
      - /sys:/sys
      - /dev:/dev
      - /etc:/etc
    network_mode: host
