version: "3"

services:

  sysinfo:
    image: sysinfo:latest
    container_name: sysinfo
    restart: on-failure
    command: [ ]
    volumes:
      - /proc:/proc:ro
      - /sys:/sys:ro
      - /dev:/dev:ro
      - /etc:/etc:ro
    network_mode: host
